### ISSUE TITLE
Black screen in BasicSample, but some console output. Iphone 7, IOS 11 beta

### ISSUE THREAD

**Issue by eighteight** [felixfaire/Cinder-ARKit#1]
```
2017-08-12 16:56:34.751102+0300 BasicSample[536:109788] [DYMTLInitPlatform] platform initialization successful
2017-08-12 16:56:34.910954+0300 BasicSample[536:109642] Metal GPU Frame Capture Enabled
2017-08-12 16:56:34.911537+0300 BasicSample[536:109642] Metal API Validation Enabled
Adding anchor point
Adding anchor point
Adding anchor point
Adding anchor point
Adding anchor point
Adding anchor point
Adding anchor point
Adding anchor point
Adding anchor point
Adding anchor point
Adding anchor point
Adding anchor point
Adding anchor point
Adding anchor point
```

**Comment by felixfaire** [comment]
When you add an anchor point by tapping it should add a white box in front of the camera. Do you not see the white boxes? If so make sure you are in a bright room with lots of visual detail / texture.

The background is currently black as I havent got round to getting the camera image as a gl texture yet. Its in a YCbCr colour space so will hopefully have the conversion implemented soon.

**Comment by felixfaire** [comment]
ps the interface is subject to change a lot over the coming couple of days as it's very bare bones at the moment so keep pulling regularly. And feel free to fork and PR changes.

**Comment by eighteight** [comment]
I only see black screen, no white boxes while tapping.

This is where I point the camera. Seems pretty bright and full of detail.

Thanks.

![file 12-08-2017 17 09 00](https://user-images.githubusercontent.com/542368/29241412-e3fabaae-7f81-11e7-81ff-a9c502b7bc2d.jpeg)

**Comment by felixfaire** [comment]
I had forgot to call run() in the example (before it ran automatically). Try again now.

**Comment by eighteight** [comment]
I now am getting white cubes and later on grayish planes, which seem to match the horizontal planes.
![file 12-08-2017 17 50 58](https://user-images.githubusercontent.com/542368/29241835-77e5cb34-7f8a-11e7-9125-2ad581cef57f.png)

**Comment by felixfaire** [comment]
Great! Thats mostly it at the moment. More functionality on the way
