### ISSUE TITLE
AR Image tracking

### ISSUE THREAD

**Issue by eighteight** [felixfaire/Cinder-ARKit#4]
Hi, I am using your block as a basis for ARKit image tracking. It was pretty easy to add ARImageAnchor tracking, however, when I draw a solid rectangle in place of the physical image, it is shifted and scaling is wrong, when I move the device:

![img_5102](https://user-images.githubusercontent.com/542368/39678292-415a0fe6-5192-11e8-9c86-eab70e05c510.JPG)

I am using a modified version of your Basic app code to draw the rectangle:

```
gl::clear( Color( 0, 0, 0 ) );
                gl::color( 1.0f, 1.0f, 1.0f, 1.0f );
                mARSession->drawRGBCaptureTexture( getWindowBounds() );
                
                gl::ScopedMatrices matScp;
                gl::setViewMatrix( mARSession->mViewMatrix );
                gl::setProjectionMatrix( mARSession->mProjectionMatrix );

                gl::ScopedGlslProg glslProg( gl::getStockShader( gl::ShaderDef().color() ));
                gl::ScopedColor colScp;
                gl::color( 1.0f, 1.0f, 1.0f );
                
                for (const auto& a : mARSession->getImageAnchors())
                {
                    gl::ScopedMatrices matScp;
                    gl::setModelMatrix( a.mTransform );
                    gl::translate( a.mPhysicalSize.x*0.5,  a.mPhysicalSize.y*0.5);
                    gl::rotate( M_PI*0.5f, vec3(1,0,0) ); // Make it parallel with the ground
                    const float xRad = a.mPhysicalSize.x * 0.5f;
                    const float zRad = a.mPhysicalSize.y * 0.5f;
                    gl::color( 0.0f, 0.6f, 0.9f, 0.2f );
                    gl::drawSolidRect( Rectf( -xRad, -zRad, xRad, zRad ));
                }
```

 In the apple's example of the image tracking, the solid rectangle matches the physical image perfectly: https://www.dropbox.com/s/oi8h2agrr0onwa0/RPReplay_Final1524654438.MP4?dl=0

Do you see any problem with this code?

I would be happy to submit a pull request once I get the image recognition working.

Thanks.

**Comment by felixfaire** [comment]
Hi eighteight. 

I got a little distracted and havent kept up with the API changes since the first version of ARKit last summer (when image tracking wasnt available). I will look into it now (and obviously accept pull requests if you have made any progress already).

**Comment by felixfaire** [comment]
It seems from the [documentation on image tracking](https://developer.apple.com/documentation/arkit/recognizing_images_in_an_ar_experience) that the orientation of the image anchor is not persistently tracked over time, it just happens once on recognition and at this point you are recommended to reset the world origin to that coordinate system and add anchors etc to this frame of reference... I havent exposed the ObjectiveC method to do this yet (ARSession setWorldOrigin(relativeTransform:)) but you can probably add it fairly easily if you are in a hurry.

I also think this shows I need a better way to add / access the anchors the user adds. will have a think

**Comment by eighteight** [comment]
@felixfaire : Thanks. I tried setting world origin while handling the anchors, but that did not fix the problem -- the rectangle is now farther away from the image in the view. This is where I set the session's world origin:

```
- (void)session:(ARSession *)session didAddAnchors:(NSArray<ARAnchor*>*)anchors
{
    for (ARAnchor* anchor in anchors)
    {
        if ([anchor isKindOfClass:[ARPlaneAnchor class]])
        {
            ARPlaneAnchor* pa = (ARPlaneAnchor*)anchor;
            ciARKitSession->mPlaneAnchors[getUidStringFromAnchor( pa )] = PlaneAnchor( toMat4( pa.transform ), toVec3( pa.center ), toVec3( pa.extent ));
        }
        else if ([anchor isKindOfClass:[ARImageAnchor class]]){
            ARImageAnchor* ia = (ARImageAnchor*) anchor;

            CGSize physSize = [[ia referenceImage] physicalSize];

            ciARKitSession->mImageAnchors[getUidStringFromAnchor( ia )] = ImageAnchor( toMat4( ia.transform ), glm::vec2(physSize.width, physSize.height), [[[ia referenceImage] name] UTF8String]);
            [session setWorldOrigin:ia.transform];
        }
        else
        {
            ciARKitSession->mAnchors[getUidStringFromAnchor( anchor )] = Anchor( toMat4( anchor.transform ));
        }
    }
}
```

I'll publish my WIP on the Cinder-ARKit in a little while.

**Comment by felixfaire** [comment]
@eighteight Hm, interesting. I'd definitely be interested in seeing your branch and adding image tracking.

On another note i have just updated / abstracted the ARKit bridge interface into a private implementation class as I think it will be better going forward. Hopefully your work on the Image tracking will be fairly easy to add into the new implementation.

**Comment by eighteight** [comment]
Yeah, I think the new design is cleaner. Unrelated though I can’t add a ARKit/ARReferenceImage.h to any place I tried - all hell breaks lose. Will have another go at it later today

**Comment by felixfaire** [comment]
@eighteight search for "#import <ARKit/ARKit.h>" and include it under there. All objective C must be in the same place, we'll have to add an interface to it though the AppleARKitSessionImpl class.

**Comment by eighteight** [comment]
PR is submitted

**Comment by felixfaire** [comment]
its working now. Will make a new sample for image tracking.
![image](https://user-images.githubusercontent.com/5576638/39827113-d2a9b5d2-53ae-11e8-94fa-8e8edc88afb2.png)
